StockWebApplication/Models/StockViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StockWebApplication.Models
{
    public class StockViewModel
    {
    }
}

StockWebApplication/Controllers/StockController.cs
using StockWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StockWebApplication.Controllers
{
    public class StockController : Controller
    {
        //
        // GET: /Stock/

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult SubmitOption(OptionViewModel model)
        {
            var x = model.OptionID;
            return new JsonResult();
        }

    }
}

StockWebApplication/Views/Stock/Index.cshtml
@{
    ViewBag.Title = "Stocks";
}

@section styles {
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Scripts/qTip/jquery.qtip.min.css")">
}
<div id="wow">
    <div class="alert alert-success alert-dismissible" role="alert" data-bind="visible: showSuccess">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" data-bind="click: dismissSuccess">
            <span aria-hidden="true">&times;</span>
        </button>
        <span>Option saved successfully.</span>
    </div>
    <div data-bind="with: currentStock">
        @*<stock-widget params="name: name, symbol: symbol, lastPrice: lastPrice, high: high, low: low, open: open"></stock-widget>*@
        <div style="width: 450px; border: 1px solid #ddd; border-radius: 5px; margin: 15px; padding: 5px;">
            <table class="table">
                <caption>
                    <span data-bind="text: name"></span>&nbsp;(<span data-bind="text: symbol"></span>)
                    <span data-bind="click: $parent.refreshCurrentStock" style="float:right; margin-right: 10px; cursor: pointer;">
                        <i class="fa fa-refresh" style="color: rgb(52, 203, 52)" data-bind="css: { 'fa-spin': $parent.isRefreshing }"></i>
                    </span>   
                </caption>                                                                                              
                <thead>
                    <tr>
                        <td>Last Price</td>                                                                             
                        <td>High</td>                                                                                   
                        <td>Low</td>                                                                                    
                        <td>Open</td>                                                                                   
                    </tr>                                                                                               
                </thead>                                                                                                
                <tbody>
                    <tr>
                        <td data-bind="currency: lastPrice"></td>                                                           
                        <td data-bind="currency: high"></td>
                        <td data-bind="currency: low"></td>
                        <td data-bind="currency: open"></td>                                                                
                    </tr>                                                                                               
                </tbody>                                                                                                
            </table>                                                                                                    
        </div>
    </div>

    <div data-bind="with: currentOption" style="width: 825px; border: 1px solid #ddd; border-radius: 5px; margin: 15px; padding: 5px;">
        <div data-bind="slideVisible: !(currentPrice() > 0)">
            Enter stock ticker: <input type="text" data-bind="value: symbol" />
            <button type="button" class="btn btn-primary" data-bind="click: $parent.getOptionStock">Lookup</button>
        </div>
        <div data-bind="slideVisible: currentPrice() > 0" style="display: none;">
            <div class="form-group">
                <label>Option Type:</label>
                <select data-bind="options: $parent.optionTypes, optionsText: 'key', optionsValue: 'value', value: optionType" class="form-control"></select>
            </div>
            <div class="form-group" data-bind="visible: optionType() == 0">
                <label>Purchase Price:</label>
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    <input type="text" class="form-control" data-bind="value: currentPrice" />
                </div>
            </div>
            <div class="form-group">
                <label>Strike Price:</label>
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    <input type="text" class="form-control" data-bind="value: strikePrice" />
                </div>
            </div>
            <div class="form-group">
                <label>Option Price:</label>
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    <input type="text" class="form-control" data-bind="value: optionPrice" />
                </div>
            </div>
            <div class="form-group">
                <label>Expiration Date:</label>
                <input type="text" data-bind="datepicker: expirationDate" />
            </div>
            <div class="form-group">
                <label>Quantity:</label>
                <input type="number" data-bind="value: quantity" />
            </div>
            <div style="padding: 5px;">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td>Exposed</td>
                            <td>Volatility</td>
                            <td>BE Price</td>
                            <td>BE Volatility</td>
                            <td>Expiration Gain</td>
                            <td>Expiration Gain %</td>
                            <td data-bind="visible: optionType() == 0">Exercise Gain</td>
                            <td data-bind="visible: optionType() == 0">Exercise Gain %</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td data-bind="currency: exposed"></td>
                            <td data-bind="percentage: strikeVolatility"></td>
                            <td data-bind="currency: breakEvenPrice"></td>
                            <td data-bind="percentage: breakEvenVolatility"></td>
                            <td data-bind="currency: expirationGain"></td>
                            <td data-bind="percentage: expirationGainPercentage"></td>
                            <td data-bind="visible: optionType() == 0, currency: exercisedGain">Exercise Gain</td>
                            <td data-bind="visible: optionType() == 0, percentage: exercisedGainPercentage">Exercise Gain %</td>
                        </tr>
                    </tbody>
                </table>  
            </div>
            <button type="button" class="btn btn-danger" data-bind="click: $parent.cancelOption">Cancel</button>
            <button type="button" class="btn btn-primary" data-bind="click: $parent.submitOption">Submit</button>
        </div>
    </div>
</div>

@section Scripts {

    <!-- site -->
    <script type="text/javascript" src="@Url.Content("~/Scripts/site/site.stock.js")"></script>

    <!-- components -->
    <script type="text/javascript" src="@Url.Content("~/Scripts/components/site.components.stock.js")"></script>

    <script>
        window.submitOptionUrl = "@Url.Action("SubmitOption", "Stock")";
        $(function () {
            site.stock.init();
        });
    </script>
}